### ISSUE TITLE
Resources are not downloaded correctly without 'mvn install' command 

### ISSUE THREAD

**Issue by imikulich** [qaprosoft/carina#1311]
**Describe the bug**
After upgrading carina core version to 7.0.3 following migration steps:

- Update in your project pom.xml version for carina-core dependency to 7.0.3
- Update in your project pom.xml com.zebrunner.agent-core version to 1.4.0
- Rebuild the project `mvn -U clean compile` 
 
the project has been rebuilt successfully. 
But after  executing  automation tests on ci the build compilation error has been detected. 

Actual behavior: the failures has been detected only by command `mvn clean install -DskipTests` or `mvn  -U clean install `
Expected behavior:  the failures should be detected  by command `mvn -U clean compile`

**Comment by DenisPitsul2020** [comment]
Reviewed code - not a problem of the carina

**Comment by imikulich** [comment]
In this case I propose add  the inctall command to addinional migration steps

**Comment by vdelendik** [comment]
fixed in migration steps:
![image](https://user-images.githubusercontent.com/4551455/115015278-13e8db80-9ebc-11eb-81e2-e747cbdcd85d.png)

**Comment by imikulich** [comment]
Thank you  carina team!

**Comment by okamara** [comment]
Verified on customer. Fixed.
